apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dnsLabel" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: {{ .Values.image }}
        name: main
