$script = <<SHELL
       apt-get install -y puppet
       puppet module install puppetlabs-apt
SHELL

Vagrant.configure(2) do |config|
	config.vm.box = "debian/jessie64"
	config.vm.box_version = "8.2.0"
	config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
    config.vm.synced_folder "../../", "/home/vagrant/stool"
    config.vm.provision "shell", inline: $script
    config.vm.provision "puppet" do |puppet|
		puppet.manifests_path = "vagrant/puppet/manifests"
	end
    config.vm.network :forwarded_port, guest: 9993, host: 7993
	config.vm.provider "virtualbox" do |v|
		v.memory = 2048
		v.cpus = 2
	end
end
