# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/vivid64"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210.box"
  #config.vm.network :private_network, ip: "192.168.33.10"
  config.vm.provider :virtualbox do |vb|
     vb.customize ["modifyvm", :id, "--memory", "2048"]
  end
  config.vm.synced_folder "../../target/", "/home/vagrant/stool-target"

  config.vm.provision "shell", inline: <<-SHELL
    set -e
    sudo apt-get update
    sudo apt-get install -y openjdk-8-jdk
    sudo dpkg -i /home/vagrant/stool-target/stool_*.deb
  SHELL
end
