# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu1204"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210.box"
  #config.vm.network :private_network, ip: "192.168.33.10"
  config.vm.provider :virtualbox do |vb|
     vb.customize ["modifyvm", :id, "--memory", "2048"]
  end
  config.vm.synced_folder "../../target/", "/home/vagrant/stool-target"

  config.vm.provision :puppet do |puppet|
     puppet.manifests_path = "puppet/"
     puppet.manifest_file  = "init.pp"
  end
end
