#!/bin/sh -e

. /usr/share/debconf/confmodule
db_version 2.0
db_get stool/home
export STOOL_SETUP_HOME=$RET
db_get stool/group
export STOOL_SETUP_GROUP=$RET
db_get stool/user
export STOOL_SETUP_USER=$RET
db_get stool/svnuser
export STOOL_SETUP_SVNUSER=$RET
db_get stool/svnpassword
export STOOL_SETUP_SVNPASSWORD=$RET

# echo "$DPKG_MAINTSCRIPT_NAME: home: $STOOL_SETUP_HOME user: $STOOL_SETUP_USER group: $STOOL_SETUP_GROUP" >> /tmp/stool-vars

if [ $DPKG_MAINTSCRIPT_NAME = "postrm" -a "$1" = "purge" ]; then
  db_purge
fi

dir=$(dirname $0)
# dir is /var/lib/dpkg/tmp.ci (when calling preinst) and /var/lib/dpkg/info (otherwise)
jar=${dir}/${DPKG_MAINTSCRIPT_PACKAGE}.postrm
if [ ! -e ${jar} ] ; then
  jar=${dir}/postrm
fi
# STOOL_SETUP_OPTS is a hook to add e.g. debugging options
# +e to get the log file written in case of an error
set +e
java $STOOL_DASHBOARD_SETUP_OPTS -cp ${jar} net.oneandone.stool.setup.DebianDashboardSetup "$@" >/tmp/stool-dashboard-setup-$DPKG_MAINTSCRIPT_NAME.log
# make sure to exit, because we might append a jar file.
exit $?
