apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-sidecar
data:
  fluent.conf: |
    <source>
      @type tail
      format none
      path /var/log/**/*.log
      path_key source_path
      pos_file /fluentd/log.pos
      read_from_head true
      tag stage.format
      <parse>
        @type none
      </parse>
    </source>

    <filter stage.format>
      @type record_transformer
      <record>
        stage "hello"
      </record>
    </filter>
    <match stage.format>
      @type forward
      send_timeout 60s
      recover_wait 10s
      hard_timeout 60s
      <server>
        name myserver1
        host collector
        port 24224
        weight 60
      </server>
    </match>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-collector
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>

    <match stage.format>
      @type file
      path /fluentd/log/${stage}/${source_path}
      <buffer stage,source_path>
        @type memory
        flush_mode interval
        flush_interval 10s
      </buffer>
      <format>
        @type single_value
      </format>
      append true
      add_path_suffix false
    </match>
---
apiVersion: v1
kind: Pod
metadata:
  name: logging
spec:
  containers:
  - name: demo
    image: busybox
    args:
    - /bin/sh
    - -c
    - >
      i=0;
      while true;
      do
        echo "$i: $(date)" >> /var/log/1.log;
        echo "$(date) INFO $i" >> /var/log/2.log;
        i=$((i+1));
        sleep 1;
      done
    volumeMounts:
    - name: varlog
      mountPath: /var/log
  - name: fluentd
    image: fluent/fluentd:v1.11.2-1.0
    volumeMounts:
    - name: varlog
      mountPath: /var/log
    - name: config-volume
      mountPath: /fluentd/etc
  volumes:
  - name: varlog
    emptyDir: {}
  - name: config-volume
    configMap:
      name: fluentd-sidecar
---
apiVersion: v1
kind: Pod
metadata:
  name: collector
  labels:
    app: collector
spec:
  containers:
    - name: collector
      image: fluent/fluentd:v1.11.2-1.0
      volumeMounts:
        - name: config-volume
          mountPath: /fluentd/etc
  volumes:
    - name: config-volume
      configMap:
        name: fluentd-collector
---
apiVersion: v1
kind: Service
metadata:
  name: collector
  namespace: test-pearl
spec:
  ports:
  - name: fluentd
    port: 24224
    protocol: TCP
    targetPort: 24224
  - name: fluentd-udp
    port: 24224
    protocol: UDP
    targetPort: 24224
  selector:
    app: collector
  type: ClusterIP

