#!/bin/sh -e

. /usr/share/debconf/confmodule

# debconf intput is connected to fd 3 now
# debconf output is connected to fd 0

dir=$(dirname $0)
# dir is /var/lib/dpkg/tmp.ci (when calling preinst) and /var/lib/dpkg/info (otherwise)
jar=${dir}/${DPKG_MAINTSCRIPT_PACKAGE}.postrm
if [ ! -e ${jar} ] ; then
  jar=${dir}/postrm
fi

# send normal output to debconf input
java ${{options}} $${{optionsVariable}} -cp ${jar} ${{main}} "$@" 1>&3

# none-null is handled by set -e
exit 0
