apiVersion: v1
data:
  fluent.conf: |
    <source>
      @type tail
      format none
      path /var/log/stool/**/*.log
      path_key source_path
      pos_file /fluentd/log.pos
      read_from_head true
      tag stage.format
      <parse>
        @type none
      </parse>
    </source>

    <filter stage.format>
      @type record_transformer
      <record>
        stage "{{ .Values.name }}"
      </record>
    </filter>
    <match stage.format>
      @type forward
      send_timeout 60s
      recover_wait 10s
      hard_timeout 60s
      <server>
        name stool
        host stool
        port 24224
        weight 60
      </server>
    </match>
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-fluentd
