apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.name }}-http
spec:
  host: {{ .Values.name }}.cp.pearl.server.lan
  path: /
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ .Values.name }}
    weight: 100
  wildcardPolicy: None
