apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.name }}-https
spec:
  host: {{ .Values.name }}.{{ .Values.fqdn }}
  port:
    targetPort: https
  tls:
    termination: passthrough
  to:
    kind: Service
    name: {{ .Values.name }}
    weight: 100
  wildcardPolicy: None
