$script = <<SHELL
       apt-get install -y puppet
       apt-get install -y subversion
       puppet module install puppetlabs-apt
SHELL

Vagrant.configure(2) do |config|
	# see https://atlas.hashicorp.com/boxes/search
    #

#    config.vm.box = "ubuntu/wily64" # Ubuntu 15.10
#    config.vm.box_version = "20151029.0.0"

#    config.vm.box = "ubuntu/vivid64" # Ubuntu 15.04
#    config.vm.box_version = "20151030.0.0"

# TODO: comes without host additions - synced_folder below fails
 	config.vm.box = "debian/contrib-jessie64"
 	config.vm.box_version = "8.3.0"

	config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
    config.vm.synced_folder "../../..", "/home/vagrant/stool/"
    config.vm.provision "shell", inline: $script
    config.vm.provision "puppet" do |puppet|
		puppet.manifests_path = "puppet/manifests"
	end
    config.vm.network :forwarded_port, guest: 9993, host: 7993
	config.vm.provider "virtualbox" do |v|
		v.memory = 2048
		v.cpus = 2
	end
end
