#!/bin/sh
dir=$(dirname $0)
# dir is /var/lib/dpkg/tmp.ci (when calling preinst) and /var/lib/dpkg/info (otherwise)
jar=${dir}/${DPKG_MAINTSCRIPT_PACKAGE}.postrm
if [ ! -e ${jar} ] ; then
  jar=${dir}/postrm
fi
java -cp ${jar} net.oneandone.stool.setup.DebianSetup "$@"
exit $?
# make sure to exit, because we might append a jar file