#!/bin/sh
dir=$(dirname $0)
# dir is /var/lib/dpkg/tmp.ci or /var/lib/dpkg/info
jar=${dir}/${DPKG_MAINTSCRIPT_PACKAGE}.postrm
if [ ! -e ${jar} ] ; then
  jar=${dir}/postrm
fi
echo jar: ${jar}
java -cp ${jar} net.oneandone.stool.setup.DebianSetup $0 "$@"
exit $?
# make sure to exit, because we might append a jar file