#!/bin/sh

### BEGIN INIT INFO
# Provides:        stool
# Required-Start:  $local_fs $remote_fs $network $syslog $named
# Required-Stop:   $local_fs $remote_fs $network $syslog $named
# Should-Start:    sssd
# Should-Stop:     sssd
# Default-Start:   2 3 4 5
# Default-Stop:    0 1 6
# Short-Description: Stage tool
### END INIT INFO

# Note: we need sssd to stop the stool service on stagehosts, otherwise sudo rejects unknown users

STOOL="/usr/share/stool/stool"
. /lib/lsb/init-functions

case "$1" in
        start)
                log_daemon_msg "Starting stages" "stool"
                $STOOL system-start
                result=$?
                log_end_msg $result
                exit $result
        ;;
        
        force-reload|restart)
                log_daemon_msg "Restarting stages" "stool"
                $STOOL system-stop
                $STOOL system-start
                result=$?
                log_end_msg $result
                exit $result
        ;;

        stop)
                log_daemon_msg "Stopping stages" "stool"
                $STOOL system-stop
                result=$?
                log_end_msg $result
                exit $result
        ;;
        
        status)
                log_daemon_msg "Listing stages" "stool"
                $STOOL list
                result=$?
                log_end_msg $result
                exit $result
        ;;

        *)
                echo "Usage: service stool {start|stop|restart|force-reload|status}"
                exit 1
        ;;
esac
