#!/bin/sh

### BEGIN INIT INFO
# Provides:        stool
# Required-Start:  $network
# Required-Stop:   $network
# Default-Start:   2 3 4 5
# Default-Stop:
# Short-Description: Start Stool stages
### END INIT INFO

STOOL=/opt/ui/opt/tools/stool/bin/stool-raw.sh
. /lib/lsb/init-functions

case "$1" in
        start)
                log_daemon_msg "Starting stages" "stool"
                sudo -u servlet $STOOL system-start
                result=$?
                log_end_msg $result
                exit $result
        ;;
        
        stop)
                log_daemon_msg "Stopping stages" "stool"
                sudo -u servlet $STOOL system-stop
                result=$?
                log_end_msg $result
                exit $result
        ;;
        
        *)
                echo "Usage: /opt/ui/etc/init.d/stool {start|stop}"
                exit 1
        ;;
esac
