#!/bin/sh

### BEGIN INIT INFO
# Provides:        stool
# Required-Start:  $local_fs $remote_fs $network $syslog $named sssd
# Required-Stop:   $local_fs $remote_fs $network $syslog $named sssd
# Default-Start:   2 3 4 5
# Default-Stop:    0 1 6
# Short-Description: Start Stool stages
### END INIT INFO

# we need sssd to stop the stool service, otherwise sudo rejects unknwon users

STOOL=/opt/ui/opt/tools/stool/bin/stool-raw.sh
. /lib/lsb/init-functions

case "$1" in
        start)
                log_daemon_msg "Starting stages" "stool"
                sudo -u servlet $STOOL system-start
                result=$?
                log_end_msg $result
                exit $result
        ;;
        
        force-reload|restart)
                log_daemon_msg "Restarting stages" "stool"
                sudo -u servlet $STOOL system-stop
                sudo -u servlet $STOOL system-start
                result=$?
                log_end_msg $result
                exit $result
        ;;

        stop)
                log_daemon_msg "Stopping stages" "stool"
                sudo -u servlet $STOOL system-stop
                result=$?
                log_end_msg $result
                exit $result
        ;;
        
        status)
                log_daemon_msg "Listing stages" "stool"
                sudo -u servlet $STOOL list
                result=$?
                log_end_msg $result
                exit $result
        ;;

        *)
                echo "Usage: /opt/ui/etc/init.d/stool {start|stop}"
                exit 1
        ;;
esac
