#!/bin/sh
dir=/opt/ui/opt/tools/stool
test -d $dir
exists=$?
set -e

# TODO: there's no package dependency for this ...
export MAVEN_HOME=/opt/ui/opt/tools/wsdtools/maven/current
/opt/ui/bin/setup-stool -v -batch ${dir}
if test $exists -eq 1; then
  chown -R root:users ${dir}/downloads ${dir}/inbox ${dir}/logs ${dir}/service-wrapper ${dir}/conf ${dir}/tomcat ${dir}/wrappers
  sudo -u servlet ${dir}/bin/stool-raw.sh chown -stage overview
fi
