#!/bin/sh
set -e

bin=/usr/share/stool
# TODO replace this check by some kind of configuration
if [ -d /opt/ui/opt/tools ] ; then
    home=/opt/ui/opt/tools/stool
    group=users
else
    home=/var/lib/stool
    group=stool
fi

if [ "$1" = "configure" ]; then
    echo  "configure home ${home}, group ${group}"
    if getent group ${group} >/dev/null 2>&1; then
        echo "re-using existing group: ${group}"
    else
        echo "creating group: ${group}"
        groupadd $group
        for file in /home/* ; do
            name=$(basename $file)
            echo "add user to group: ${name}"
            usermod -a -G ${group} ${name}
        done
    fi
    if id -u servlet >/dev/null 2>&1; then
        echo "re-using existing user: servlet"
        if groups servlet | grep -q -w ${group} ; then
            echo "servlet user already in group ${group}"
        else
            echo "add servlet user to group ${group}"
            usermod -a -G ${group} ${name}
        fi
    else
        echo "creating user: servlet"
        # TODO --no-create-home
        adduser --system --quiet --ingroup ${group} --home /home/servlet servlet
    fi
    ln -s ${home} ${bin}/home

    # TODO: should be possible to generate overview without MAVEN_HOME
    export MAVEN_HOME=/not/used/for/overview/stage
    STOOL_BIN=${bin} sg ${group} "java -cp ${bin}/stool.jar net.oneandone.stool.setup.DebianHome ${home}"
    sudo -u servlet ${bin}/stool-raw.sh chown -stage overview

    update-rc.d stool defaults
fi
