#!/bin/sh

bin=/usr/share/stool
if [ -d /opt/ui/opt/tools ] ; then
    home=/opt/ui/opt/tools/stool
else
    home=/var/lib/stool
fi
test -d ${home}
exists=$?
set -e

if [ "$1" = "configure" ]; then
    if id -u servlet >/dev/null 2>&1; then
        echo "servlet user already exists"
    else
        # TODO --no-create-home
        adduser --system --quiet --ingroup users --home /home/servlet servlet
    fi
    ln -s ${home} ${bin}/home

    # TODO: there's no package dependency for this ...
    export MAVEN_HOME=/opt/ui/opt/tools/wsdtools/maven/current
    STOOL_BIN=${bin} java -cp ${bin}/stool.jar net.oneandone.stool.setup.DebianHome ${home}
    if test ${exists} -eq 1; then
      chown -R root:users ${home}
    fi
    sudo -u servlet ${bin}/stool-raw.sh chown -stage overview

    update-rc.d stool defaults
fi
