#!/bin/sh

set -e

case "$1" in
    remove)
        # may fail if setup did not complete properly
        service stool stop || echo service shutdown failed
        update-rc.d stool remove
    ;;
    upgrade)
        # TODO: reject new stool invocations
        # TODO: stop stool overview
    ;;
    deconfigure|failed-upgrade)
    ;;
    *)
        echo "prerm called with unknown argument: $1"
    ;;
esac
exit 0
