#!/bin/sh

set -e

case "$1" in
    remove)
        rm -rf /opt/ui/opt/tools/stool
    ;;
    upgrade|deconfigure|failed-upgrade)
    ;;
    *)
        echo "prerm called with unknown argument: $1"
    ;;
esac
exit 0
