{{ if eq .Values.fqdn "localhost" }}
apiVersion: v1
kind: Service
metadata:
  name: stool
  namespace: stool
spec:
  ports:
    - name: http
      nodePort: 31000
      port: 80
      targetPort: 8080
    - name: fluentd-tcp
      port: 24224
      protocol: TCP
      targetPort: 24224
    - name: fluentd-udp
      port: 24224
      protocol: UDP
      targetPort: 24224
  selector:
    app: stool
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: stool-registry
  namespace: stool
spec:
  ports:
    - nodePort: 31500
      port: 5000
  selector:
    app: stool-registry
  type: NodePort
{{ else }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-routes
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: default
  podSelector: {}
  policyTypes:
    - Ingress
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: stool-https-route
spec:
  host: {{ .Values.fqdn }}
  port:
    targetPort: https
  tls:
    termination: passthrough
  to:
    kind: Service
    name: stool
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stool-account
---
apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  name: stool-admin-binding
roleRef:
  name: admin
subjects:
  - kind: ServiceAccount
    name: stool-account
---
apiVersion: v1
data:
  ssh_host_rsa_key: {{ .Values.hostkey }}
  ssh_host_rsa_key.pub: {{ .Values.hostkeyPub }}
kind: Secret
metadata:
  name: stool-hostkey
---
apiVersion: v1
binaryData:
  cert.sh: {{ .Values.certScript }}
kind: ConfigMap
metadata:
  name: stool-cert-script
---
apiVersion: v1
kind: Service
metadata:
  name: stool
spec:
  ports:
    - name: https
      port: 443
      targetPort: 8080
    - name: fluentd-tcp
      port: 24224
      protocol: TCP
      targetPort: 24224
    - name: fluentd-udp
      port: 24224
      protocol: UDP
      targetPort: 24224
  selector:
    app: stool
  type: ClusterIP
{{ end }}
{{ if .Values.cert }}
---
apiVersion: v1
binaryData:
  tomcat.p12: {{ .Values.cert }}
kind: ConfigMap
metadata:
  name: stool-cert
{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stool-log-collector
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>

    <match stage.format>
      @type file
      path /fluentd/log/${stage}/${source_path}
      <buffer stage,source_path>
        @type memory
        flush_mode interval
        flush_interval 10s
      </buffer>
      <format>
        @type single_value
      </format>
      append true
      add_path_suffix false
    </match>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stool
  {{- if eq .Values.fqdn "localhost" }}
  namespace: stool
  {{- end }}
  labels:
    app: stool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stool
  template:
    metadata:
      labels:
        app: stool
    spec:
      {{- if ne .Values.fqdn "localhost" }}
      serviceAccountName: stool-account
      {{- end }}
      containers:
      - name: stool
        image: {{ .Values.repositoryTag }}
        resources:
          limits:
            cpu: 2
          requests:
            cpu: 200m
        volumeMounts:
          - mountPath: /etc/fault
            name: fault
          - mountPath: /var/log/stages
            name: fluentd-logs
      {{- if .Values.cert }}
          - mountPath: /usr/local/tomcat/conf/tomcat.p12
            name: cert-volume
            subPath: tomcat.p12
      {{- end }}
      {{- if ne .Values.fqdn "localhost" }}
          - mountPath: /var/lib/stool/cert.sh
            name: cert-script-volume
            subPath: cert.sh
      {{- end }}
        env:
        - name: FQDN
          value: "{{ .Values.fqdn }}"
        - name: REGISTRY_URL
          value: "{{ .Values.registryUrl }}"
        - name: API
          value: "{{ .Values.api }}"
        - name: OPTS
          value: "--add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED --illegal-access=deny -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,quiet=n,address=*:5005{{ if ne .Values.fqdn "localhost" }} -Dserver.ssl.key-store-type=PKCS12 -Dserver.ssl.key-store=/usr/local/tomcat/conf/tomcat.p12 -Dserver.ssl.key-store-password=changeit -Dserver.ssl.key-alias=tomcat -Dsecurity.require-ssl=true{{ end }}"
        - name: LDAP_URL
          value: "{{ .Values.ldapUrl }}"
        - name: LDAP_UNIT
          value: "{{ .Values.ldapUnit }}"
        - name: LDAP_PRINCIPAL
          value: "{{ .Values.ldapPrincipal }}"
        - name: LDAP_CREDENTIALS
          value: "{{ .Values.ldapCredentials }}"
        - name: LDAP_SSO
          value: "{{ .Values.ldapSso }}"
        - name: ADMIN
          value: "{{ .Values.admin }}"
        - name: AUTO_REMOVE
          value: "{{ .Values.autoRemove }}"
        - name: DEFAULT_EXPIRE
          value: "{{ .Values.defaultExpire }}"
        - name: ENGINE_LOG
          value: "{{ .Values.engineLog }}"
        - name: ENVIRONMENT
          value: "{{ .Values.environment }}"
        - name: LOGLEVEL
          value: "{{ .Values.loglevel }}"
        - name: MAIL_HOST
          value: "{{ .Values.mailHost }}"
        - name: MAIL_USERNAME
          value: "{{ .Values.username }}"
        - name: MAIL_PASSWORD
          value: "{{ .Values.password }}"
        - name: DISK_QUOTA
          value: "{{ .Values.diskQuota }}"
        - name: MEMORY_QUOTA
          value: "{{ .Values.memoryQuota }}"

{{- if ne .Values.fqdn "localhost" }}
      - name: fault-update
        image: {{ .Values.repositoryTag }}
        command: ["sh"]
        args: ["-c", "while true; do sleep 7200; fault '-user=[{{ .Values.faultName }}:/etc/ssh/ssh_host_rsa_key]' auth && fault install -dest=/etc/fault/workspace -permissions=/etc/fault/workspace.permissions -batch @ >/etc/fault/install.log 2>&1; done"]
        resources:
          limits:
            cpu: 1
          requests:
            cpu: 200m
        volumeMounts:
          - mountPath: /etc/fault
            name: fault
            readOnly: true
          - mountPath: /etc/ssh
            name: hostkey-volume
{{- end }}
      - name: collector
        image: fluent/fluentd:v1.11.2-1.0
        volumeMounts:
          - name: fluentd-config
            mountPath: /fluentd/etc
          - name: fluentd-logs
            mountPath: /fluentd/log
{{- if ne .Values.fqdn "localhost" }}
      initContainers:
      - name: fault-setup
        image: {{ .Values.repositoryTag }}
        command: ["sh"]
        args: ["-c", "mkdir /etc/fault/workspace && fault '-user=[{{ .Values.faultName }}:/etc/ssh/ssh_host_rsa_key]' auth && fault install -dest=/etc/fault/workspace -permissions=/etc/fault/workspace.permissions -batch @"]
        resources:
          limits:
            cpu: 1
          requests:
            cpu: 200m
        volumeMounts:
          - mountPath: /etc/fault
            name: fault
          - mountPath: /etc/ssh
            name: hostkey-volume
{{- end }}
      volumes:
      - name: fluentd-config
        configMap:
          name: stool-log-collector
      - name: fluentd-logs
        emptyDir: {}
{{- if eq .Values.fqdn "localhost" }}
      - name: fault
        hostPath:
          path: /Users/mhm/.fault
          type: Directory
{{- else }}
      - name: fault
        emptyDir: {}
      - name: hostkey-volume
        secret:
          secretName: stool-hostkey
      - name: cert-script-volume
        configMap:
          items:
            - key: cert.sh
              path: cert.sh
              mode: 0755
          name: stool-cert-script
{{- end }}
{{- if .Values.cert }}
      - name: cert-volume
        configMap:
          items:
            - key: tomcat.p12
              path: tomcat.p12
          name: stool-cert
{{- end}}