{{ if eq .Values.fqdn "localhost" }}
apiVersion: v1
kind: Service
metadata:
  name: stool-registry
  namespace: stool
spec:
  ports:
    - nodePort: 31500
      port: 5000
  selector:
    app: stool-registry
  type: NodePort
{{ else }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-routes
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: default
  podSelector: {}
  policyTypes:
    - Ingress
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: stool-https-route
spec:
  host: {{ .Values.fqdn }}
  port:
    targetPort: https
  tls:
    termination: passthrough
  to:
    kind: Service
    name: stool
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stool-account
---
# caution: RoleBinding is not available in kubernetes
apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  name: stool-admin-binding
roleRef:
  name: admin
subjects:
  - kind: ServiceAccount
    name: stool-account
{{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: stool
spec:
  ports:
    - name: https
      {{- if eq .Values.fqdn "localhost" }}
      nodePort: 31000
      {{- end }}
      port: 443
      targetPort: 8080
    - name: fluentd-tcp
      port: 24224
      protocol: TCP
      targetPort: 24224
    - name: fluentd-udp
      port: 24224
      protocol: UDP
      targetPort: 24224
  selector:
    app: stool
  type: {{ if eq .Values.fqdn "localhost" }}NodePort{{ else }}ClusterIP{{ end }}
