#!/bin/sh -e

. /usr/share/debconf/confmodule
db_version 2.0
db_input low stool-dashboard/user || true
db_input low stool-dashboard/svnuser || true
db_input low stool-dashboard/svnpassword || true
db_go
