apiVersion: v1
kind: ConfigMap
metadata:
  name: sc-yaml
data:
  .sc.yaml: |
    registryCredentials: "{{ .Values.registryCredentials }}"
    charts: "/etc/charts"
    currentContext: "localhost"
    lib: "/var/lib/stool"
    logs: "/var/log/stool"
    contexts:
      - name: "localhost"
        url: "local:local"
