{{ if .Values.cert }}
---
apiVersion: v1
binaryData:
  tomcat.p12: {{ .Values.cert }}
kind: ConfigMap
metadata:
  name: stool-cert
{{ end }}
{{ if .Values.certScript }}
---
apiVersion: v1
binaryData:
  cert.sh: {{ .Values.certScript }}
kind: ConfigMap
metadata:
  name: stool-cert-script
{{ end }}
{{ if .Values.faultName }}
---
apiVersion: v1
data:
  ssh_host_rsa_key: {{ .Values.faultHostkey }}
  ssh_host_rsa_key.pub: {{ .Values.faultHostkeyPub }}
kind: Secret
metadata:
  name: stool-hostkey
{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stool-log-collector
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>

    <match stage.format>
      @type file
      path /fluentd/log/${stage}/${source_path}
      <buffer stage,source_path>
        @type memory
        flush_mode interval
        flush_interval 10s
      </buffer>
      <format>
        @type single_value
      </format>
      append true
      add_path_suffix false
    </match>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stool
  labels:
    app: stool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stool
  template:
    metadata:
      # https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: stool
    spec:
      {{- if ne .Values.fqdn "localhost" }}
      serviceAccountName: stool-account
      {{- end }}
      containers:
      - name: stool
        image: {{ .Values.repositoryTag }}
        readinessProbe:
          httpGet:
            {{- if .Values.cert }}
            scheme: HTTPS
            {{- end }}
            path: /api/version
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 2
          requests:
            cpu: 200m
        volumeMounts:
          - mountPath: /usr/local/sc/configuration.yaml
            subPath: configuration.yaml
            name: configuration
          - mountPath: /etc/fault
            name: fault
          - mountPath: /usr/local/sc/charts
            name: charts
          - mountPath: /usr/local/sc/logs
            name: fluentd-logs
      {{- if .Values.cert }}
          - mountPath: /usr/local/tomcat/conf/tomcat.p12
            name: cert-volume
            subPath: tomcat.p12
      {{- end }}
      {{- if .Values.certScript }}
          - mountPath: /var/lib/stool/cert.sh
            name: cert-script-volume
            subPath: cert.sh
      {{- end }}
        env:
        - name: OPTS
          value: "--add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED --illegal-access=deny -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,quiet=n,address=*:5005{{ if .Values.cert }} -Dserver.ssl.key-store-type=PKCS12 -Dserver.ssl.key-store=/usr/local/tomcat/conf/tomcat.p12 -Dserver.ssl.key-store-password=changeit -Dserver.ssl.key-alias=tomcat -Dsecurity.require-ssl=true{{ end }}"
{{- if .Values.faultName }}
      - name: fault-update
        image: {{ .Values.repositoryTag }}
        command: ["sh"]
        args: ["-c", "while true; do sleep 7200; fault '-user=[{{ .Values.faultName }}:/etc/ssh/ssh_host_rsa_key]' auth && fault install -dest=/etc/fault/workspace -permissions=/etc/fault/workspace.permissions -batch @ >/etc/fault/install.log 2>&1; done"]
        resources:
          limits:
            cpu: 1
          requests:
            cpu: 200m
        volumeMounts:
          - mountPath: /etc/fault
            name: fault
            readOnly: true
          - mountPath: /etc/ssh
            name: hostkey-volume
{{- end }}
      - name: collector
        image: contargo.server.lan/cisoops-public/github/fluent/fluentd:v1.11.2-1.0
        volumeMounts:
          - name: fluentd-config
            mountPath: /fluentd/etc
          - name: fluentd-logs
            mountPath: /fluentd/log
      initContainers:
      - name: init-charts
        image: {{ .Values.repositoryTag }}
        command: ["sh"]
        args: ["-c", "cd /tmp && git clone {{ .Values.charts }} charts && cp -r charts /etc"]
        resources:
          limits:
            cpu: 1
          requests:
            cpu: 200m
        volumeMounts:
        - mountPath: /etc/charts
          name: charts
{{- if .Values.faultName }}
      - name: init-fault
        image: {{ .Values.repositoryTag }}
        command: ["sh"]
        args: ["-c", "mkdir /etc/fault/workspace && fault '-user=[{{ .Values.faultName }}:/etc/ssh/ssh_host_rsa_key]' auth && fault install -dest=/etc/fault/workspace -permissions=/etc/fault/workspace.permissions -batch @"]
        resources:
          limits:
            cpu: 1
          requests:
            cpu: 200m
        volumeMounts:
          - mountPath: /etc/fault
            name: fault
          - mountPath: /etc/ssh
            name: hostkey-volume
{{- end }}
      volumes:
      - name: configuration
        configMap:
          name: configuration
          items:
            - key: configuration.yaml
              path: configuration.yaml
      - name: charts
        emptyDir: {}
      - name: fluentd-config
        configMap:
          name: stool-log-collector
      - name: fluentd-logs
        emptyDir: {}
{{- if eq .Values.fqdn "localhost" }}
      - name: fault
        hostPath:
          path: /Users/mhm/.fault
          type: Directory
{{- else }}
      - name: fault
        emptyDir: {}
{{- end }}
{{- if .Values.faultName }}
      - name: hostkey-volume
        secret:
          secretName: stool-hostkey
{{- end }}
{{- if .Values.cert }}
      - name: cert-volume
        configMap:
          items:
            - key: tomcat.p12
              path: tomcat.p12
          name: stool-cert
{{- end}}
{{- if .Values.certScript }}
      - name: cert-script-volume
        configMap:
          items:
            - key: cert.sh
              path: cert.sh
              mode: 0755
          name: stool-cert-script
{{- end}}
