{{ if .Values.cert }}
---
apiVersion: v1
binaryData:
  tomcat.p12: {{ .Values.cert }}
kind: ConfigMap
metadata:
  name: stool-cert
{{ end }}
{{ if .Values.faultName }}
---
apiVersion: v1
data:
  ssh_host_rsa_key: {{ .Values.faultHostkey }}
  ssh_host_rsa_key.pub: {{ .Values.faultHostkeyPub }}
kind: Secret
metadata:
  name: stool-hostkey
{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stool-log-collector
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>

    <match stage.format>
      @type file
      path /fluentd/log/${stage}/${source_path}
      <buffer stage,source_path>
        @type memory
        flush_mode interval
        flush_interval 10s
      </buffer>
      <format>
        @type single_value
      </format>
      append true
      add_path_suffix false
    </match>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stool
  labels:
    app: stool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stool
  template:
    metadata:
      # https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: stool
    spec:
      {{- if ne .Values.fqdn "localhost" }}
      serviceAccountName: stool-account
      {{- end }}
      containers:
      - name: stool
        image: {{ .Values.repositoryTag }}
        readinessProbe:
          httpGet:
            {{- if .Values.cert }}
            scheme: HTTPS
            {{- end }}
            path: /api/version
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 2
          requests:
            cpu: 200m
        volumeMounts:
          - mountPath: /usr/local/stool/settings.yaml
            subPath: settings.yaml
            name: settings
          - mountPath: /usr/local/stool/logs
            name: fluentd-logs
      {{- if .Values.cert }}
          - mountPath: /usr/local/tomcat/conf/tomcat.p12
            name: cert-volume
            subPath: tomcat.p12
      {{- end }}
        env:
        - name: SC_OPTS
          value: "--add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,quiet=n,address=*:5005{{ if .Values.cert }} -Dserver.ssl.key-store-type=PKCS12 -Dserver.ssl.key-store=/usr/local/tomcat/conf/tomcat.p12 -Dserver.ssl.key-store-password=changeit -Dserver.ssl.key-alias=tomcat -Dsecurity.require-ssl=true{{ end }}"
      - name: collector
        image: contargo.server.lan/cisoops-public/github/fluent/fluentd:v1.11.2-1.0
        volumeMounts:
          - name: fluentd-config
            mountPath: /fluentd/etc
          - name: fluentd-logs
            mountPath: /fluentd/log
      volumes:
      - name: settings
        configMap:
          name: settings
          items:
            - key: settings.yaml
              path: settings.yaml
      - name: fluentd-config
        configMap:
          name: stool-log-collector
      - name: fluentd-logs
        emptyDir: {}
{{- if .Values.cert }}
      - name: cert-volume
        configMap:
          items:
            - key: tomcat.p12
              path: tomcat.p12
          name: stool-cert
{{- end}}
