{{ if ne .Values.fqdn "localhost" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-routes
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: default
  podSelector: {}
  policyTypes:
    - Ingress
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: stool-https-route
spec:
  host: {{ .Values.fqdn }}
  port:
    targetPort: https
  tls:
    termination: passthrough
  to:
    kind: Service
    name: stool
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stool-account
---
# caution: RoleBinding is not available in kubernetes
apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  name: stool-admin-binding
roleRef:
  name: admin
subjects:
  - kind: ServiceAccount
    name: stool-account
{{ end }}
