apiVersion: v1
kind: ConfigMap
metadata:
  name: settings
data:
  settings.yaml: |
    loglevel: "{{ .Values.loglevel }}"
    currentContext: "localhost"
    local:
      registryCredentials: "{{ .Values.registryCredentials }}"
      stageLogs: "{{ .Values.stageLogs }}"
      toolkit: "{{ .Values.toolkit }}"
      fqdn: "{{ .Values.fqdn }}"
      kubernetes: "{{ .Values.kubernetes }}"
      ldapUrl: "{{ .Values.ldapUrl }}"
      ldapUnit: "{{ .Values.ldapUnit }}"
      ldapPrincipal: "{{ .Values.ldapPrincipal }}"
      ldapCredentials: "{{ .Values.ldapCredentials }}"
      ldapSso: "{{ .Values.ldapSso }}"
      admin: "{{ .Values.admin }}"
      autoRemove: "{{ .Values.autoRemove }}"
      environment:
        {{- range $key, $val := .Values.environment }}
        {{ $key }}: {{ $val | quote }}
        {{- end }}
      mailHost: "{{ .Values.mailHost }}"
      mailUsername: "{{ .Values.username }}"
      mailPassword: "{{ .Values.password }}"
