apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-routes
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: default
  podSelector: {}
  policyTypes:
    - Ingress
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: stool-https-route
spec:
  host: ${host}
  port:
    targetPort: https
  tls:
    termination: passthrough
  to:
    kind: Service
    name: stool-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stool-account
---
apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  name: stool-admin-binding
roleRef:
  name: admin
subjects:
  - kind: ServiceAccount
    name: stool-account
---
apiVersion: v1
data:
  ssh_host_rsa_key: ${hostkey}
  ssh_host_rsa_key.pub: ${hostkey-pub}
kind: Secret
metadata:
  name: stool-hostkey
---
apiVersion: v1
binaryData:
  tomcat.p12: ${cert}
kind: ConfigMap
metadata:
  name: stool-cert
---
apiVersion: v1
binaryData:
  cert.sh: ${cert-script}
kind: ConfigMap
metadata:
  name: stool-cert-script
---
apiVersion: v1
kind: Service
metadata:
  name: stool-service
spec:
  ports:
    - name: https
      port: 443
      targetPort: 8080
  selector:
    app: stool
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stool
  labels:
    app: stool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stool
  template:
    metadata:
      labels:
        app: stool
    spec:
      serviceAccountName: stool-account
      containers:
      - name: stool
        image: ${repositoryTag}
        resources:
          limits:
            cpu: 2
          requests:
            cpu: 200m
        volumeMounts:
          - mountPath: /etc/ssh
            name: hostkey-volume
          - mountPath: /usr/local/tomcat/conf/tomcat.p12
            name: cert-volume
            subPath: tomcat.p12
          - mountPath: /var/lib/stool/cert.sh
            name: cert-script-volume
            subPath: cert.sh
        env:
        - name: HOST
          value: "${host}"
        - name: OPTS
          value: "--add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED --illegal-access=deny -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,quiet=n,address=*:31001 -Dserver.ssl.key-store-type=PKCS12 -Dserver.ssl.key-store=/usr/local/tomcat/conf/tomcat.p12 -Dserver.ssl.key-store-password=changeit -Dserver.ssl.key-alias=tomcat -Dsecurity.require-ssl=true"
        - name: ENGINE_LOG
          value: "false"
        - name: VHOSTS
          value: "false"
        - name: LDAP_UNIT
          value: "cisostages"
        - name: LDAP_URL
          value: "ldaps://ldap.1and1.org:636/ou=ims_service,o=1und1,c=DE"
        - name: LDAP_PRINCIPAL
          value: "uid=cisostages,ou=accounts,ou=ims_service,o=1und1,c=DE"
        - name: LDAP_CREDENTIALS
          value: "MzJmMWRhOG"
        - name: LDAP_SSO
          value: "https://login.1and1.org/ims-sso"
        - name: JMX_USAGE
          value: "jconsole -J-Djava.class.path=$CISOTOOLS_HOME/stool/opendmk_jmxremote_optional_jar-1.0-b01-ea.jar service:jmx:jmxmp://localhost:%d"
        - name: ADMIN
          value: "michael.hartmeier@ionos.com"
        - name: REGISTRY_URL
          value: "${portus}"
        - name: LOGLEVEL
          value: "INFO"
      volumes:
        - name: hostkey-volume
          secret:
            secretName: stool-hostkey
        - name: cert-volume
          configMap:
            items:
              - key: tomcat.p12
                path: tomcat.p12
            name: stool-cert
        - name: cert-script-volume
          configMap:
            items:
              - key: cert.sh
                path: cert.sh
                mode: 0755
            name: stool-cert-script
