apiVersion: v1
kind: Namespace
metadata:
  name: stool
---
apiVersion: v1
kind: Service
metadata:
  name: stool-server-http
  namespace: stool
spec:
  ports:
    - name: http
      nodePort: 31000
      port: 80
      targetPort: 8080
    - name: fluentd-tcp
      port: 24224
      protocol: TCP
      targetPort: 24224
    - name: fluentd-udp
      port: 24224
      protocol: UDP
      targetPort: 24224
  selector:
    app: stool
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: stool-registry
  namespace: stool
spec:
  ports:
  - nodePort: 31500
    port: 5000
  selector:
    app: stool-registry
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stool
  namespace: stool
  labels:
    app: stool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stool
  template:
    metadata:
      labels:
        app: stool
    spec:
      containers:
      - name: stool
        image: contargo.server.lan/cisoops-public/stool-server:latest
        imagePullPolicy: Never
        env:
          - name: HOST
            value: "${host}"
          - name: API
            value: "${api}"
          - name: OPTS
            value: "--add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED --illegal-access=deny -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,quiet=n,address=*:5005 -Dserver.ssl.key-store-type=PKCS12 -Dserver.ssl.key-store=/usr/local/tomcat/conf/tomcat.p12 -Dserver.ssl.key-store-password=changeit -Dserver.ssl.key-alias=tomcat -Dsecurity.require-ssl=true"
          - name: ENGINE_LOG
            value: "false"
          - name: VHOSTS
            value: "false"
          - name: LDAP_UNIT
            value: "${ldapUnit}"
          - name: LDAP_URL
            value: "${ldapUrl}"
          - name: LDAP_PRINCIPAL
            value: "${ldapPrincipal}"
          - name: LDAP_CREDENTIALS
            value: "${ldapCredentials}"
          - name: LDAP_SSO
            value: "${ldapSso}"
          - name: JMX_USAGE
            value: "jconsole -J-Djava.class.path=$CISOTOOLS_HOME/stool/opendmk_jmxremote_optional_jar-1.0-b01-ea.jar service:jmx:jmxmp://localhost:%d"
          - name: ADMIN
            value: "michael.hartmeier@ionos.com"
          - name: REGISTRY_URL
            value: "${portus}"
          - name: LOGLEVEL
            value: "INFO"


volumeMounts:
${mounts}      volumes:
${volumes}
