apiVersion: v1
kind: Namespace
metadata:
  name: stool
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stool-log-collector
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>

    <match stage.format>
      @type file
      path /fluentd/log/\${stage}/\${source_path}
      <buffer stage,source_path>
        @type memory
        flush_mode interval
        flush_interval 10s
      </buffer>
      <format>
        @type single_value
      </format>
      append true
      add_path_suffix false
    </match>
---
apiVersion: v1
kind: Service
metadata:
  name: stool-server-http
  namespace: stool
spec:
  ports:
    - name: http
      nodePort: 31000
      port: 80
      targetPort: 8080
    - name: fluentd-tcp
      port: 24224
      protocol: TCP
      targetPort: 24224
    - name: fluentd-udp
      port: 24224
      protocol: UDP
      targetPort: 24224
  selector:
    app: stool
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: stool-registry
  namespace: stool
spec:
  ports:
  - nodePort: 31500
    port: 5000
  selector:
    app: stool-registry
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stool
  namespace: stool
  labels:
    app: stool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stool
  template:
    metadata:
      labels:
        app: stool
    spec:
      containers:
      - name: stool
        image: contargo.server.lan/cisoops-public/stool-server:latest
        resources:
          limits:
            cpu: 2
          requests:
            cpu: 200m
        imagePullPolicy: Never
        volumeMounts:
          - mountPath: /etc/fault
            name: fault
            readOnly: true
          - mountPath: /var/log/stages
            name: fluentd-logs
        env:
          - name: HOST
            value: "${host}"
          - name: API
            value: "${api}"
          - name: OPTS
            value: "--add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED --illegal-access=deny -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,quiet=n,address=*:5005"
          - name: ENGINE_LOG
            value: "false"
          - name: VHOSTS
            value: "false"
          - name: LDAP_URL
            value: ""
          - name: ADMIN
            value: "michael.hartmeier@ionos.com"
          - name: REGISTRY_URL
            value: "${portus}"
          - name: LOGLEVEL
            value: "INFO"
      - name: collector
        image: fluent/fluentd:v1.11.2-1.0
        volumeMounts:
          - name: fluentd-config
            mountPath: /fluentd/etc
          - name: fluentd-logs
            mountPath: /fluentd/log
      volumes:
      - name: fault
        hostPath:
          path: ${home}/.fault
          type: Directory
      - name: fluentd-config
        configMap:
          name: stool-log-collector
      - name: fluentd-logs
        emptyDir: {}
