apiVersion: v1
binaryData:
  fluent.conf: PHNvdXJjZT4KICBAdHlwZSB0YWlsCiAgZm9ybWF0IG5vbmUKICBwYXRoIC92YXIvbG9nL3N0b29sLyoqLyoubG9nCiAgcGF0aF9rZXkgc291cmNlX3BhdGgKICBwb3NfZmlsZSAvZmx1ZW50ZC9sb2cucG9zCiAgcmVhZF9mcm9tX2hlYWQgdHJ1ZQogIHRhZyBzdGFnZS5mb3JtYXQKICA8cGFyc2U+CiAgICBAdHlwZSBub25lCiAgPC9wYXJzZT4KPC9zb3VyY2U+Cgo8ZmlsdGVyIHN0YWdlLmZvcm1hdD4KICBAdHlwZSByZWNvcmRfdHJhbnNmb3JtZXIKICA8cmVjb3JkPgogICAgc3RhZ2UgIm1obSIKICA8L3JlY29yZD4KPC9maWx0ZXI+CjxtYXRjaCBzdGFnZS5mb3JtYXQ+CiAgQHR5cGUgZm9yd2FyZAogIHNlbmRfdGltZW91dCA2MHMKICByZWNvdmVyX3dhaXQgMTBzCiAgaGFyZF90aW1lb3V0IDYwcwogIDxzZXJ2ZXI+CiAgICBuYW1lIHN0b29sCiAgICBob3N0IHN0b29sCiAgICBwb3J0IDI0MjI0CiAgICB3ZWlnaHQgNjAKICA8L3NlcnZlcj4KPC9tYXRjaD4K
kind: ConfigMap
metadata:
  name: mhm-fluentd
