apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mhm-http
spec:
  host: mhm.cp.pearl.server.lan
  path: /
  port:
    targetPort: http
  to:
    kind: Service
    name: mhm
    weight: 100
  wildcardPolicy: None
